// Common
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const ALERT_NOTIFICATION = 'ALERT_NOTIFICATION'
export const ALERT_MESSAGE = 'ALERT_MESSAGE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const LOAD_TOKEN = 'LOAD_TOKEN'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
